SELECT G.GroupID
	,G.GroupName
	,G.Description
	,RI.SERIAL_NO
	,R.RECORDER_ID
	,RI.CONFIG_TYPEID
	,RI.START_TIME
	,RI.END_TIME
	,R.GPS
	,R.POLE_NO
FROM [General_LR4].[dbo].[Groups] G
FULL OUTER JOIN RECORDER_INSTALL_TABLE RI
  ON G.GroupID = RI.GROUP_ID  
FULL OUTER JOIN [General_LR4].[dbo].[RECORDER] R
  ON RI.RECORDER_ID = R.RECORDER_ID
WHERE [ParentID] IN
  (SELECT GroupID FROM [General_LR4].[dbo].[Groups] WHERE [ParentID] IN
   (SELECT GroupID FROM [General_LR4].[dbo].[Groups] WHERE [ParentID] IN
    (SELECT GroupID FROM [General_LR4].[dbo].[Groups] WHERE [ParentID] IS NULL)))

SELECT RI.SERIAL_NO
	,R.RECORDER_ID
	,RI.CONFIG_TYPEID
	,RI.START_TIME
	,RI.END_TIME
	,R.GPS
	,R.POLE_NO
FROM [General_LR4].[dbo].[RECORDER] R
FULL OUTER JOIN RECORDER_INSTALL_TABLE RI
  ON R.RECORDER_ID = RI.RECORDER_ID
ORDER BY START_TIME

SELECT COUNT(*) FROM [General_LR4].[dbo].[RECORDER] R
FULL OUTER JOIN RECORDER_INSTALL_TABLE RI
  ON R.RECORDER_ID = RI.RECORDER_ID
  WHERE R.GPS != '00.0000 00.0000' AND R.GPS != '0.00000 0.00000'
